### ISSUE TITLE
menu option

### ISSUE THREAD

**Issue by amerem3** [FiveM-Scripts/fs_freemode#52]
Can the vehicle inventory be made optional? when I press the Y button on my controller it pops up and i am not sure how to change it. I also just want to handle my cars with garages....

**Comment by ghermans** [comment]
Thanks for bringing this to our attention, to be honest i never verified if the current control binding would cause any conflict with controllers.

I will provide a fix later today.

**Comment by amerem3** [comment]
Sweet thanks!

**Comment by amerem3** [comment]
When might this fix be available?

**Comment by ghermans** [comment]
The fix is available in the [hotfix](https://github.com/FiveM-Scripts/fs_freemode/tree/hotfix) branch. 
Once you download it, open **config.lua** and change the value for **Setup.InventoryKey**
for example:    

**F9 - default button**
```Lua
Setup.InventoryKey = 56
```
to    

**HOME button**
```Lua
Setup.InventoryKey = 213
```

You can find a complete list of all the controls [here](https://wiki.fivem.net/wiki/Controls)

**Comment by amerem3** [comment]
oh ok thanks!

**Comment by amerem3** [comment]
I set it to 213 and not its on RB button....

**Comment by ghermans** [comment]
As a said in my previous reply you can find a complete list of all the controls [here](https://wiki.fivem.net/wiki/Controls) change the value to something that works for you.
